services:
   db:
     image: postgres:latest
     ports:
      - '5432:5432'
     environment:
        - POSTGRES_USER=//your DB user
        - POSTGRES_PASSWORD= // your password
        - POSTGRES_DB=social_network