export enum ConfigKeys {
  // DB CONFIG KEYS
  DATABASE_URL = 'DATABASE_URL',

  // APP Configs
  PORT = 'PORT',
  APP_ENV = 'APP_ENV',
  GRAPHQL_PLAYGROUND_ENABLED = 'GRAPHQL_PLAYGROUND_ENABLED',

  NODE_ENV = 'NODE_ENV',
}
